name: contact1313
description: "A new Flutter project."

publish_to: 'none' # Prevent publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0" # Adjusted based on Flutter and Dart compatibility.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2           # For HTTP requests.
  flutter_dotenv: ^5.0.2 # For managing environment variables.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Recommended lints for coding practices.

flutter:
  uses-material-design: true

  # Uncomment if assets are needed.
  # assets:
  #   - images/example.png

  # Uncomment for custom fonts.
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
